name: CI

on:
  push:
  workflow_dispatch:

# permissions:
#   contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: go mod download
        run: go mod download
      - name: go mod verify
        run: go mod verify
      - name: generate command strings
        run: go generate ./...
      - name: "Place wintun.dll"
        run: cp deps/wintun/bin/amd64/wintun.dll ./ 
      - name: build
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --rm-dist
      - name: Run tests
        run: go test ./...
